// apps/game/src/pages/settings/songs/[path].tsx
import { useNavigate, useParams } from "@solidjs/router";
import KeyHints from "~/components/key-hints";
import Layout from "~/components/layout";
import Menu, { type MenuItem } from "~/components/menu";
import TitleBar from "~/components/title-bar";
import { songsStore } from "~/stores/songs";

export default function SongPathSettings() {
  const navigate = useNavigate();

  const onBack = () => navigate("/settings/songs");

  const params = useParams<{ path: string }>();
  const path = () => decodeURIComponent(params.path);

  const removePath = () => {
    songsStore.removeSongPath(path());
    onBack();
  };

  const menuItems: MenuItem[] = [
    {
      type: "button",
      label: "Remove",
      action: removePath,
    },
  ];

  return (
    <Layout
      intent="secondary"
      header={<TitleBar title="Settings" description={`Songs / ${path()}`} onBack={onBack} />}
      footer={<KeyHints hints={["back", "navigate", "confirm"]} />}
    >
      <Menu items={menuItems} onBack={onBack} />
    </Layout>
  );
}

// apps/game/src/routes/settings/songs/[path].tsx
import { useNavigate, useParams } from "@solidjs/router";
import { createSignal } from "solid-js";
import KeyHints from "~/components/key-hints";
import Layout from "~/components/layout";
import TitleBar from "~/components/title-bar";
import Button from "~/components/ui/button";
import { useNavigation } from "~/hooks/navigation";
import { songsStore } from "~/stores/songs";

export default function SongPathSettings() {
  const navigate = useNavigate();
  const [pressed, setPressed] = createSignal(false);

  const onBack = () => navigate("/settings/songs");

  const params = useParams<{ path: string }>();
  const path = () => decodeURIComponent(params.path);

  const removePath = () => {
    songsStore.removeSongPath(path());
    onBack();
  };

  useNavigation(() => ({
    layer: 0,
    onKeydown(event) {
      if (event.action === "back") {
        onBack();
      } else if (event.action === "confirm") {
        setPressed(true);
      }
    },
    onKeyup(event) {
      if (event.action === "confirm") {
        setPressed(false);
        removePath();
      }
    },
  }));

  return (
    <Layout
      intent="secondary"
      header={<TitleBar title="Settings" description={`Songs / ${path()}`} onBack={onBack} />}
      footer={<KeyHints hints={["back", "navigate", "confirm"]} />}
    >
      <div class="flex w-full flex-grow flex-col justify-center">
        <Button
          selected
          gradient="gradient-settings"
          onClick={() => {
            removePath();
            onBack();
          }}
          active={pressed()}
        >
          Remove
        </Button>
      </div>
    </Layout>
  );
}
