// apps/tauri/src/pages/settings/songs/index.vue
<script setup lang="ts">
import { open } from '@tauri-apps/api/dialog'
import type { MenuNavigationEvent } from '~/composables/useMenuNavigation'

const router = useRouter()
const songsStore = useSongsStore()

const back = () => {
  if (loading.value) return
  router.push({ name: '/settings/' })
}

const maxPosition = computed(() => {
  const length = songsStore.paths.length
  if (length >= 5) {
    return length - 1
  }
  return songsStore.paths.length
})

const { position, increment, decrement } = useLoop(maxPosition)

useMenuNavigation(useRepeatThrottleFn(e => onNavigate(e), 150))

const onNavigate = (event: MenuNavigationEvent) => {
  if (event.action === 'back') {
    back()
  } else if (event.action === 'confirm') {
    if (position.value === maxPosition.value) {
      pickFolder()
    } else {
      toPath(position.value)
    }
  } else if (event.action === 'left') {
    decrement()
  } else if (event.action === 'right') {
    increment()
  }
}

const loading = ref(false)

const pickFolder = async () => {
  if (loading.value) return
  loading.value = true

  const path = await open({ directory: true, recursive: true })

  if (path && !Array.isArray(path)) {
    songsStore.addPath(path)
  }
  loading.value = false
}

const toPath = (index: number) => {
  if (loading.value) return
  router.push({ name: '/settings/songs/[id]', params: { id: index } })
}

const folderName = (path: string) => {
  const unixPath = path.replace(/\\/g, '/')
  const name = unixPath.split('/').pop()
  return name || 'Error'
}

const gradient = { start: '#36D1DC', end: '#5B86E5' }

const select = useSoundEffect('select')
watch(position, () => select.play())

const confirm = useSoundEffect('confirm')

onBeforeUnmount(() => {
  confirm.play()
})
</script>

<template>
  <Layout class="gradient-bg-secondary" @back="back">
    <template #header>
      <TitleBar title="Settings" description="Songs" @back="back" />
    </template>
    <div class="flex flex justify-center items-center gap-1cqw">
      <IconButton
        v-for="path, index in songsStore.paths"
        :key="path"
        :active="index === position"
        :label="folderName(path)"
        icon="Folder"
        :gradient="gradient"
        :loading="false"
        class="w-1/11"
        @mouseenter="() => (position = index)"
        @click="toPath(index)"
      />
      <IconButton
        v-if="songsStore.paths.length < 5"
        :active="position === maxPosition"
        label="Add"
        icon="Plus"
        :gradient="gradient"
        :loading="loading"
        class="w-1/11"
        @mouseenter="() => (position = maxPosition)"
        @click="pickFolder"
      />
    </div>
    <template #footer>
      <KeyHints :hints="['back', 'navigate', 'confirm']" />
    </template>
  </Layout>
</template>

// apps/game/src/routes/settings/songs/index.tsx
import { useNavigate } from "@solidjs/router";
import { open } from "@tauri-apps/plugin-dialog";
import { type Component, For, createMemo, createSignal } from "solid-js";
import { withQuery } from "ufo";
import KeyHints from "~/components/key-hints";
import Layout from "~/components/layout";
import TitleBar from "~/components/title-bar";
import IconButton from "~/components/ui/icon-button";
import { createLoop } from "~/hooks/loop";
import { useNavigation } from "~/hooks/navigation";
import { addSongPath, songsSettings } from "~/stores/songs";
import IconFolder from "~icons/lucide/folder";
import IconPlus from "~icons/lucide/plus";

export default function SongsSettings() {
  const [pressed, setPressed] = createSignal(false);
  const [loading, setLoading] = createSignal(false);
  const navigate = useNavigate();
  const onBack = () => {
    if (songsSettings.dirty) {
      navigate(withQuery("/loading", { redirect: "/settings" }));
      return;
    }
    navigate("/settings");
  };

  const pickFolder = async () => {
    if (loading()) return;
    setLoading(true);

    const path = await open({
      directory: true,
      recursive: true,
    });

    if (path) {
      addSongPath(path);
    }

    setLoading(false);
  };

  const folderName = (path: string) => {
    const unixPath = path.replace(/\\/g, "/");
    const name = unixPath.split("/").pop();
    return name || "Unknown";
  };

  const buttons = createMemo(() => {
    const buttons: {
      label: string;
      icon: Component<{ class?: string }>;
      action?: () => void;
      loading?: boolean;
    }[] = [];
    for (const path of songsSettings.paths) {
      buttons.push({ label: folderName(path), icon: IconFolder, action: () => navigate(`/settings/songs/${encodeURIComponent(path)}`) });
    }
    buttons.push({ label: "Add", icon: IconPlus, action: pickFolder, loading: loading() });

    return buttons;
  });

  const { position, increment, decrement, set } = createLoop(() => buttons().length);

  useNavigation(() => ({
    layer: 0,
    onKeydown(event) {
      if (event.action === "back") {
        onBack();
      } else if (event.action === "left") {
        decrement();
      } else if (event.action === "right") {
        increment();
      } else if (event.action === "confirm") {
        setPressed(true);
      }
    },
    onKeyup(event) {
      if (event.action === "confirm") {
        setPressed(false);
        const button = buttons()[position()];
        button?.action?.();
      }
    },
  }));

  return (
    <Layout
      intent="secondary"
      header={<TitleBar title="Settings" description="Songs" onBack={onBack} />}
      footer={<KeyHints hints={["back", "navigate", "confirm"]} />}
    >
      <div class="flex w-full flex-grow items-center justify-center gap-1cqw">
        <For each={buttons()}>
          {(button, index) => (
            <IconButton
              onClick={() => button.action?.()}
              onMouseEnter={() => set(index())}
              selected={position() === index()}
              active={pressed() && position() === index()}
              loading={button.loading}
              icon={button.icon}
              label={button.label}
              gradient="gradient-settings"
            />
          )}
        </For>
      </div>
    </Layout>
  );
}
