// apps/electron/src/renderer/src/components/Avatar.vue
<script setup lang="ts">
const props = defineProps<{
  src?: string
  alt?: string
  username?: string
}>()

const error = ref(false)

const onError = () => {
  error.value = true
}

watch(() => props.src, (src) => {
  // set error to true if no src is provided or if src is empty
  error.value = !src || src === ''
}, { immediate: true })

const initials = computed(() => {
  if (props.username) {
    return props.username[0].toUpperCase()
  }
  return '?'
})
</script>

<template>
  <img v-if="!error" class="h-2cqw w-2cqw rounded-full" :src="props.src" @error="onError">
  <div v-else class="inline-block h-2cqw w-2cqw bg-blue-500 rounded-full text-white flex items-center justify-center text-1cqw overflow-hidden">
    {{ initials }}
  </div>
</template>

// apps/game/src/components/avatar.tsx
import { Show, createEffect, createSignal, on } from "solid-js";

interface AvatarProps {
  src?: string;
  fallback?: string;
  class?: string;
}

export default function Avatar(props: AvatarProps) {
  const [error, setError] = createSignal(false);

  createEffect(
    on(
      () => props.src,
      () => {
        setError(false);
      }
    )
  );

  const fallback = () => props.fallback?.at(0) || "?";

  return (
    <div
      class="grid h-10 w-10"
      classList={{
        [props.class || ""]: !!props.class,
      }}
    >
      <div class="col-start-1 row-start-1 flex h-full w-full items-center justify-center rounded-full bg-gradient-to-rt from-cyan-400 to-blue-500">
        {fallback()}
      </div>
      <Show when={!error()}>
        <img
          onError={() => setError(true)}
          src={props.src || props.fallback}
          alt={props.fallback || "Avatar"}
          class="col-start-1 row-start-1 block h-full w-full rounded-full"
        />
      </Show>
    </div>
  );
}
