// apps/tauri/src/components/TitleBar.vue
<script setup lang="ts">
const props = withDefaults(
  defineProps<{
    title: string
    description?: string
    backArrow?: boolean
  }>(),
  {
    backArrow: true,
    description: undefined,
  }
)

const emit = defineEmits<{
  (e: 'back'): void
}>()
</script>
<template>
  <div class="flex flex-row items-center gap-0.5cqw font-semibold uppercase text-neutral-400">
    <button v-if="props.backArrow" class="i-sing-chevron-left text-2cqw" @click="emit('back')"></button>
    <div class="text-1.3cqw -mt-0.15cqw">
      {{ props.title }}
    </div>
    <div v-if="props.description" class="mt-0.25cqw text-0.8cqw">/ {{ props.description }}</div>
  </div>
</template>

<style scoped></style>

// apps/game/src/components/title-bar.tsx
import { Show } from "solid-js";
import IconChevronLeft from "~icons/lucide/chevron-left";

interface TitleBarProps {
  title: string;
  description?: string;
  onBack?: () => void;
}

export default function TitleBar(props: TitleBarProps) {
  return (
    <div class="flex items-center gap-0.5cqw font-semibold text-base uppercase">
      <Show when={props.onBack}>
        <button class="flex items-center gap-0.5cqw" onClick={props.onBack} type="button">
          <IconChevronLeft />
        </button>
      </Show>
      <div>
        {props.title}
        <Show when={props.description}>
          <span class="pl-2 text-xs">/ {props.description}</span>
        </Show>
      </div>
    </div>
  );
}
