// apps/game/src/pages/home.tsx
import { useNavigate } from "@solidjs/router";
import { createQuery } from "@tanstack/solid-query";
import { type Component, For, Show, createSignal } from "solid-js";
import { Dynamic } from "solid-js/web";
import Avatar from "~/components/avatar";
import KeyHints from "~/components/key-hints";
import Layout from "~/components/layout";
import { createLoop } from "~/hooks/loop";
import { useNavigation } from "~/hooks/navigation";
import { createQRCode } from "~/hooks/qrcode";
import { lobbyQueryOptions } from "~/lib/queries";
import { useLobbyStore } from "~/stores/lobby";
import IconMicVocal from "~icons/lucide/mic-vocal";
import IconPartyPopper from "~icons/lucide/party-popper";
import IconSettings from "~icons/lucide/settings";
import IconUsers from "~icons/lucide/users";

export default function Home() {
  const navigate = useNavigate();
  const lobbyStore = useLobbyStore();
  const [pressed, setPressed] = createSignal(false);

  const cards = [
    {
      label: "Sing",
      gradient: "gradient-sing",
      icon: IconMicVocal,
      description: "Sing your favorite songs, alone or with your friends!",
      action: () => navigate("/sing"),
    },
    {
      label: "Party",
      gradient: "gradient-party",
      icon: IconPartyPopper,
      description: "Battle it out with your friends in one of the different party game modes!",
    },
    {
      label: "Lobby",
      gradient: "gradient-lobby",
      icon: IconUsers,
      description: "Manage the party you are in and invite your friends.",
    },
    {
      label: "Settings",
      gradient: "gradient-settings",
      icon: IconSettings,
      description: "Change your settings or add your songs and microphones.",
      action: () => navigate("/settings"),
    },
  ];

  const { position, increment, decrement, set } = createLoop(4);

  useNavigation(() => ({
    layer: 0,
    onKeydown(event) {
      if (event.action === "left") {
        decrement();
      } else if (event.action === "right") {
        increment();
      } else if (event.action === "confirm") {
        setPressed(true);
      }
    },
    onKeyup(event) {
      if (event.action === "confirm") {
        setPressed(false);
        const card = cards[position()];
        card?.action?.();
      }
    },
  }));

  const qrcode = createQRCode(() => `${import.meta.env.VITE_APP_URL}/join/${lobbyStore.lobby()?.lobby.id}`, {
    type: "image/webp",
    width: 1024,
  });

  const lobbyQuery = createQuery(() => lobbyQueryOptions());

  return (
    <Layout
      header={
        <div class="flex justify-between">
          <div />
          <div class="flex gap-2">
            <For each={lobbyQuery.data?.users}>{(user) => <Avatar src={user.picture || undefined} fallback={user.username || "?"} />}</For>
          </div>
        </div>
      }
      footer={<KeyHints hints={["navigate", "confirm"]} />}
    >
      <div class="flex flex-grow flex-col gap-[6cqh]">
        <div class="flex flex-grow">
          <div class="flex-grow" />
          <Show when={lobbyStore.lobby()}>
            {(lobby) => (
              <div class="flex items-end">
                <div class="flex gap-8">
                  <div class="flex flex-col items-end justify-center">
                    <span class="font-bold text-7xl">{lobby().lobby.id}</span>
                    <span class="text-sm">{import.meta.env.VITE_APP_URL}/join</span>
                  </div>
                  <Show when={qrcode()}>{(qrcode) => <img src={qrcode()} alt="" class="h-[25cqh] rounded-lg" />}</Show>
                </div>
              </div>
            )}
          </Show>
        </div>
        <div class="flex gap-4">
          <For each={cards}>
            {(card, index) => (
              <ModeCard
                selected={position() === index()}
                active={pressed() && position() === index()}
                class="flex-1"
                label={card.label}
                gradient={card.gradient}
                icon={card.icon}
                description={card.description}
                onMouseEnter={() => set(index())}
                onClick={card.action}
              />
            )}
          </For>
        </div>
      </div>
    </Layout>
  );
}

interface ModeCardProps {
  selected?: boolean;
  active?: boolean;
  label: string;
  class?: string;
  gradient?: string;
  icon?: Component<{ class?: string }>;
  description?: string;
  onMouseEnter?: () => void;
  onClick?: () => void;
}
function ModeCard(props: ModeCardProps) {
  return (
    <button
      class="flex transform flex-col gap-1.5 p-1 transition-all ease-in-out active:scale-95"
      type="button"
      classList={{
        [props.class || ""]: true,
        "opacity-50": !props.selected,
        "scale-95": props.active,
      }}
      onMouseEnter={props.onMouseEnter}
      onClick={props.onClick}
    >
      <div class="font-semibold text-sm uppercase">{props.label}</div>
      <div
        class="flex w-full flex-grow flex-col shadow-xl"
        classList={{
          "overflow-hidden rounded-lg": props.selected,
        }}
      >
        <div
          class="flex items-center justify-center rounded-t-lg bg-gradient-to-b px-12 py-16 transition-all"
          classList={{
            [props.gradient || ""]: true,
            "rounded-b-lg": !props.selected,
          }}
        >
          <Dynamic class="text-6xl" component={props.icon} />
        </div>
        <div
          class="flex-grow rounded-b-md bg-white px-8 py-4 text-left font-semibold text-base text-black transition-all"
          classList={{
            "opacity-0": !props.selected,
          }}
        >
          {props.description}
        </div>
      </div>
    </button>
  );
}

// apps/tauri/src/pages/home.vue
<script setup lang="ts">
import { useQRCode } from '@vueuse/integrations/useQRCode'
import type * as icons from '~/logic/ui/icons'
import type { MenuNavigationEvent } from '~/composables/useMenuNavigation'

const router = useRouter()
const lobbyStore = useLobbyStore()
const songsStore = useSongsStore()
const settingsStore = useSettingsStore()
const { client } = useTRPC()

const webUrl = import.meta.env.VITE_WEB_URL

const joinUrl = computed(() => {
  if (!lobbyStore.lobby) return 'Error'
  return `${webUrl}/join/${lobbyStore.lobby.code}`
})

const qrcode = useQRCode(joinUrl, {
  type: 'image/webp',
})

const checkNeededSettings = () => {
  if (songsStore.songs.size === 0) {
    if (error.value) return
    error.value = 'You have no songs added. Go to settings and add your UltraStar songs.'
    setTimeout(() => {
      error.value = undefined
    }, 3000)
    return false
  } else if (settingsStore.microphones.length === 0) {
    if (error.value) return
    error.value = 'You have no microphones added. Go to settings and add your microphones.'
    setTimeout(() => {
      error.value = undefined
    }, 3000)
    return false
  }
  return true
}

const goToSongs = () => {
  if (!checkNeededSettings()) return
  router.push({ name: '/songs' })
}

const goToParty = async () => {
  if (!checkNeededSettings()) return

  if (lobbyStore.offline) {
    if (error.value) return
    error.value = 'You cannot play party games in offline mode. Restart the game in online mode.'
    setTimeout(() => {
      error.value = undefined
    }, 3000)
    return
  }

  if (settingsStore.microphones.length < 2) {
    if (error.value) return
    error.value = 'You need 2 microphones to play party games. Go to settings and add more microphones.'
    setTimeout(() => {
      error.value = undefined
    }, 3000)
    return
  }

  const users = await fallback()
  if (users.length < 2) {
    if (error.value) return
    error.value = 'You need at least 2 players to play party games. Find some friends and invite them to your lobby.'
    setTimeout(() => {
      error.value = undefined
    }, 3000)
    return
  }

  router.push({ name: '/party/' })
}

const cards: {
  icon: keyof typeof icons
  title: string
  gradient: { start: string; end: string }
  action: () => void
  animation?: 'spin' | 'pulse'
  description: string
}[] = [
  {
    icon: 'VinylRecord',
    title: 'Sing',
    gradient: { start: '#11998e', end: '#38ef7d' },
    action: goToSongs,
    animation: 'spin',
    description: 'Sing your favorite songs, alone or with your friends!',
  },
  {
    icon: 'Dice',
    title: 'Party Games',
    gradient: { start: '#7420FB', end: '#CF56E3' },
    action: goToParty,
    animation: 'pulse',
    description: 'Battle it out with your friends in one of the different party game modes!',
  },
  {
    icon: 'Group',
    title: 'Lobby',
    gradient: { start: '#c94b4b', end: '#ffc0cb' },
    action: () => router.push({ name: '/lobby/' }),
    animation: 'pulse',
    description: 'Manage the party you are in and invite your friends.',
  },
  {
    icon: 'Gear',
    title: 'Settings',
    gradient: { start: '#36D1DC', end: '#5B86E5' },
    action: () => router.push({ name: '/settings/' }),
    animation: 'spin',
    description: 'Change your settings or add your songs and microphones.',
  },
]

const { position, increment, decrement } = useLoop(cards.length - 1)
useMenuNavigation(useRepeatThrottleFn((e) => onNavigate(e), 150))
const onNavigate = (event: MenuNavigationEvent) => {
  if (event.action === 'confirm') {
    cards[position.value].action()
  } else if (event.action === 'right') {
    increment()
  } else if (event.action === 'left') {
    decrement()
  }
}

const queryUsers = async () => {
  const lobbyStatus = await client.lobby.status.query()
  return lobbyStatus.lobby.users
}

const fallback = useOfflineFallbackFn(queryUsers, async () => [])

const status = useQuery({
  queryKey: ['queryStatus'],
  queryFn: fallback,
  retry: 2,
  retryDelay: 0,
  refetchOnWindowFocus: false,
  cacheTime: 10000, // 10 seconds
  refetchInterval: 10000, // 10 seconds
})

const select = useSoundEffect('select')
watch(position, () => select.play())

const confirm = useSoundEffect('confirm')

onBeforeUnmount(() => {
  confirm.play()
})

const error = ref()
</script>

<template>
  <Layout class="gradient-bg-main">
    <template #header>
      <div class="flex justify-between items-center">
        <div class="uppercase font-bold text-2cqw">Tune Perfect</div>
        <div class="flex gap-0.2cqw">
          <Avatar
            v-for="user in status.data.value?.slice(0, 15)"
            :key="user.id"
            :username="user.username"
            :src="user.picture ?? undefined"
          />
        </div>
      </div>
    </template>
    <div class="flex flex-col items-center justify-center py-5cqh h-full">
      <div class="w-full h-3/7 flex items-center gap-2cqw">
        <div class="flex-grow flex">
          <div
            class="flex bg-red-600 rounded-0.45cqw p-1cqw max-w-30cqw items-center gap-0.7cqw"
            :class="[!error ? 'opacity-0' : 'transition-opacity']"
          >
            <Icon icon="Info" class="text-2.5cqw" />
            <div class="text-1cqw">
              {{ error }}
            </div>
          </div>
        </div>
        <template v-if="lobbyStore.lobby">
          <div class="text-right">
            <p class="font-bold text-4cqw leading-tight">
              {{ lobbyStore.lobby.code }}
            </p>
            <p class="text-0.8cqw text-neutral-300">{{ webUrl }}/join</p>
          </div>
          <div class="h-1/2">
            <img :src="qrcode" alt="QR Code" class="rounded-1.5cqh h-full" />
          </div>
        </template>
      </div>
      <div class="h-4/7 w-full flex gap-1cqw">
        <ModeCard
          v-for="(card, index) in cards"
          :key="card.title"
          class="flex-1"
          :title="card.title"
          :gradient="card.gradient"
          :description="card.description"
          :icon="card.icon"
          :active="position === index"
          :animation="card.animation"
          @mouseenter="() => (position = index)"
          @click="card.action"
        />
      </div>
    </div>
    <template #footer>
      <KeyHints :hints="['navigate', 'confirm']" />
    </template>
  </Layout>
</template>
