// apps/electron/src/renderer/src/pages/home.vue
<script setup lang="ts">
import { useQRCode } from '@vueuse/integrations/useQRCode'
import type * as icons from '@renderer/logic/ui/icons'
import type { MenuNavigationEvent } from '@renderer/composables/useMenuNavigation'

const router = useRouter()
const lobbyStore = useLobbyStore()

const webUrl = import.meta.env.RENDERER_VITE_WEB_URL

const joinUrl = computed(() => {
  if (!lobbyStore.lobby) return 'Error'
  return `${webUrl}/join/${lobbyStore.lobby.code}`
})

const qrcode = useQRCode(joinUrl, {
  type: 'image/webp',
})

const cards: {
  icon: keyof typeof icons
  title: string
  gradient: { start: string; end: string }
  action: () => void
  animation?: 'spin' | 'pulse'
  description: string
}[] = [
  {
    icon: 'VinylRecord',
    title: 'Sing',
    gradient: { start: '#11998e', end: '#38ef7d' },
    action: () => router.push('/sing'),
    animation: 'spin',
    description: 'Sing your favorite songs, alone or with your friends!',
  },
  {
    icon: 'Dice',
    title: 'Party Games',
    gradient: { start: '#7420FB', end: '#CF56E3' },
    action: () => router.push('/party'),
    animation: 'pulse',
    description:
      'Battle it out with your friends in one of the different party game modes!',
  },
  {
    icon: 'Group',
    title: 'Lobby',
    gradient: { start: '#c94b4b', end: '#ffc0cb' },
    action: () => router.push('/lobby'),
    animation: 'pulse',
    description: 'Manage the party you are in and invite your friends.',
  },
  {
    icon: 'Gear',
    title: 'Settings',
    gradient: { start: '#36D1DC', end: '#5B86E5' },
    action: () => router.push('/settings'),
    animation: 'spin',
    description: 'Change your settings or add your songs and microphones.',
  },
]

const { position, increment, decrement } = useLoop(cards.length - 1)
useMenuNavigation(useRepeatThrottleFn(e => onNavigate(e), 150))
const onNavigate = (event: MenuNavigationEvent) => {
  if (event.action === 'confirm') {
    cards[position.value].action()
  } else if (event.action === 'right') {
    increment()
  } else if (event.action === 'left') {
    decrement()
  }
}
</script>

<template>
  <Layout class="gradient-bg-main">
    <template #header>
      <div class="uppercase font-bold text-2cqw">
        Tune Perfect
      </div>
    </template>
    <div class="flex flex-col items-center justify-center px-5cqw py-5cqh">
      <div class="w-full h-3/7 flex justify-end items-center gap-2cqw">
        <template v-if="lobbyStore.lobby">
          <div class="text-right">
            <p class="font-bold text-4cqw leading-tight">
              {{ lobbyStore.lobby.code }}
            </p>
            <p class="text-0.8cqw text-neutral-300">
              {{ webUrl }}/join
            </p>
          </div>
          <div class="h-1/2">
            <img :src="qrcode" alt="QR Code" class="rounded-1.5cqh h-full">
          </div>
        </template>
      </div>
      <div class="h-4/7 w-full flex gap-1cqw">
        <ModeCard
          v-for="card, index in cards"
          :key="card.title"
          class="flex-1"
          :title="card.title"
          :gradient="card.gradient"
          :description="card.description"
          :icon="card.icon"
          :active="position === index"
          :animation="card.animation"
          @mouseenter="() => (position = index)"
          @click="card.action"
        />
      </div>
    </div>
    <template #footer>
      <KeyHints :hints="['navigate', 'confirm']" />
    </template>
  </Layout>
</template>

// apps/game/src/pages/home.tsx
import { useNavigate } from "@solidjs/router";
import { type Component, For, Show, createSignal } from "solid-js";
import { Dynamic } from "solid-js/web";

import KeyHints from "~/components/key-hints";
import Layout from "~/components/layout";
import { createLoop } from "~/hooks/loop";
import { useNavigation } from "~/hooks/navigation";
import { createQRCode } from "~/hooks/qrcode";
import { useLobbyStore } from "~/stores/lobby";
import IconMicVocal from "~icons/lucide/mic-vocal";
import IconPartyPopper from "~icons/lucide/party-popper";
import IconSettings from "~icons/lucide/settings";
import IconUsers from "~icons/lucide/users";

export default function Home() {
  const navigate = useNavigate();
  const lobbyStore = useLobbyStore();
  const [pressed, setPressed] = createSignal(false);

  const cards = [
    {
      label: "Sing",
      gradient: "gradient-sing",
      icon: IconMicVocal,
      description: "Sing your favorite songs, alone or with your friends!",
      action: () => navigate("/sing"),
    },
    {
      label: "Party",
      gradient: "gradient-party",
      icon: IconPartyPopper,
      description: "Battle it out with your friends in one of the different party game modes!",
    },
    {
      label: "Lobby",
      gradient: "gradient-lobby",
      icon: IconUsers,
      description: "Manage the party you are in and invite your friends.",
    },
    {
      label: "Settings",
      gradient: "gradient-settings",
      icon: IconSettings,
      description: "Change your settings or add your songs and microphones.",
      action: () => navigate("/settings"),
    },
  ];

  const { position, increment, decrement, set } = createLoop(4);

  useNavigation(() => ({
    layer: 0,
    onKeydown(event) {
      if (event.action === "left") {
        decrement();
      } else if (event.action === "right") {
        increment();
      } else if (event.action === "confirm") {
        setPressed(true);
      }
    },
    onKeyup(event) {
      if (event.action === "confirm") {
        setPressed(false);
        const card = cards[position()];
        card?.action?.();
      }
    },
  }));

  const qrcode = createQRCode(() => `${import.meta.env.VITE_APP_URL}/join/${lobbyStore.lobby()?.lobby.id}`, {
    type: "image/webp",
    width: 1024,
  });

  return (
    <Layout footer={<KeyHints hints={["navigate", "confirm"]} />}>
      <div class="flex flex-grow">
        <div class="flex-grow" />
        <Show when={qrcode()}>{(qrcode) => <img src={qrcode()} alt="" class="h-25cqh rounded-lg" />}</Show>
      </div>
      <div class="flex gap-1cqw">
        <For each={cards}>
          {(card, index) => (
            <ModeCard
              selected={position() === index()}
              active={pressed() && position() === index()}
              class="flex-1"
              label={card.label}
              gradient={card.gradient}
              icon={card.icon}
              description={card.description}
              onMouseEnter={() => set(index())}
              onClick={card.action}
            />
          )}
        </For>
      </div>
    </Layout>
  );
}

interface ModeCardProps {
  selected?: boolean;
  active?: boolean;
  label: string;
  class?: string;
  gradient?: string;
  icon?: Component<{ class?: string }>;
  description?: string;
  onMouseEnter?: () => void;
  onClick?: () => void;
}
function ModeCard(props: ModeCardProps) {
  return (
    <button
      class="flex transform flex-col gap-0.3cqw p-1 transition-all ease-in-out active:scale-95"
      type="button"
      classList={{
        [props.class || ""]: true,
        "bg-white": props.selected,
        "opacity-50": !props.selected,
        "scale-95": props.active,
      }}
      onMouseEnter={props.onMouseEnter}
      onClick={props.onClick}
    >
      <div class="font-semibold text-sm uppercase">{props.label}</div>
      <div
        class="flex w-full flex-grow flex-col shadow-xl"
        classList={{
          "overflow-hidden rounded-lg": props.selected,
        }}
      >
        <div
          class="flex items-center justify-center rounded-t-lg bg-gradient-to-b px-3cqw py-4cqw transition-all"
          classList={{
            [props.gradient || ""]: true,
            "rounded-b-lg": !props.selected,
          }}
        >
          <Dynamic class="text-6xl" component={props.icon} />
        </div>
        <div
          class="flex-grow rounded-b-md bg-white px-2cqw py-1cqw text-left font-semibold text-base text-black transition-all"
          classList={{
            "opacity-0": !props.selected,
          }}
        >
          {props.description}
        </div>
      </div>
    </button>
  );
}
