// apps/electron/src/renderer/src/pages/index.vue
<script setup lang="ts">
import type { MenuNavigationEvent } from '@renderer/composables/useMenuNavigation'
import { useMutation } from '@tanstack/vue-query'

const { client } = useTRPC()

const lobbyStore = useLobbyStore()
const router = useRouter()

const createLobby = () => client.lobby.create.mutate()

const { isLoading, isError, mutate } = useMutation({
  mutationFn: createLobby,
  retry: 4,
  retryDelay: 1000,
  onSuccess: (data) => {
    lobbyStore.jwt = data.jwt
    router.push('/home')
  },
})
mutate()

const buttons = [
  { text: 'Retry', action: () => mutate() },
  {
    text: 'Offline',
    action: () => {
      lobbyStore.offline = true
      router.push('/home')
    },
  }]

const { position, increment, decrement } = useLoop(buttons.length - 1)

useMenuNavigation(useRepeatThrottleFn(e => onNavigate(e), 150))

const onNavigate = (event: MenuNavigationEvent) => {
  if (isLoading.value) return

  if (event.action === 'confirm') {
    buttons.at(position.value)?.action()
  } else if (event.action === 'right') {
    increment()
  } else if (event.action === 'left') {
    decrement()
  }
}

const gradient = { start: '#11998ec5', end: '#38ef7dc5' }
</script>

<template>
  <Layout class="gradient-bg-main">
    <div class="flex flex-col items-center justify-center text-2cqw">
      <Icon v-if="isLoading" icon="Spinner" class="text-5cqw animate-spin" />
      <div v-if="isError" class="flex flex-col items-center gap-8cqh">
        <p class="text-2cqw font-semibold">
          Could not connect to server.
        </p>
        <div class="flex gap-1cqw">
          <Button
            v-for="button, index in buttons"
            :key="button.text"
            :active="position === index"
            :gradient="gradient"
            @mouseenter="() => position = index"
            @click="button.action"
          >
            {{ button.text }}
          </Button>
        </div>
      </div>
    </div>
    <template #footer>
      <KeyHints :hints="['navigate', 'confirm']" />
    </template>
  </Layout>
</template>

// apps/game/src/pages/index.tsx
import { useNavigate } from "@solidjs/router";
import { createMutation } from "@tanstack/solid-query";
import { For, Match, Switch, createSignal, onMount } from "solid-js";
import { withQuery } from "ufo";
import KeyHints from "~/components/key-hints";
import Layout from "~/components/layout";
import Button from "~/components/ui/button";
import { createLoop } from "~/hooks/loop";
import { useNavigation } from "~/hooks/navigation";
import { v1 } from "~/lib/api";
import { lobbyStore } from "~/stores/lobby";
import IconLoaderCircle from "~icons/lucide/loader-circle";

export default function Index() {
  const navigate = useNavigate();

  const createLobbyMutation = createMutation(() => ({
    mutationKey: ["createLobby"],
    mutationFn: async () => {
      const response = await v1.lobbies.post();

      if (response.ok) {
        return response.data;
      }

      throw new Error("Failed to create lobby");
    },
    onSuccess: (data) => {
      lobbyStore.setLobby({ token: data.token, lobby: { id: data.lobby.id } });
      goToLoading();
    },
  }));

  const goToLoading = () => navigate(withQuery("/loading", { redirect: "/home" }));

  onMount(() => {
    createLobbyMutation.mutate();
  });

  const [pressed, setPressed] = createSignal(false);

  const onBack = () => navigate("/home");
  const buttons = [
    {
      label: "Retry",
      action: () => createLobbyMutation.mutate(),
    },
    {
      label: "Play Offline",
      action: goToLoading,
    },
  ];

  const { position, increment, decrement, set } = createLoop(buttons.length);

  useNavigation(() => ({
    layer: 0,
    onKeydown(event) {
      if (event.action === "back") {
        onBack();
      } else if (event.action === "up") {
        decrement();
      } else if (event.action === "down") {
        increment();
      } else if (event.action === "confirm") {
        setPressed(true);
      }
    },
    onKeyup(event) {
      if (event.action === "confirm") {
        setPressed(false);
        buttons[position()]?.action();
      }
    },
  }));

  return (
    <Layout intent="primary" footer={<KeyHints hints={["navigate", "confirm"]} />}>
      <Switch>
        <Match when={createLobbyMutation.isPending}>
          <div class="flex flex-grow items-center justify-center">
            <IconLoaderCircle class="animate-spin text-6xl" />
          </div>
        </Match>
        <Match when={createLobbyMutation.isError}>
          <div class="flex w-full flex-grow flex-col justify-center">
            <h1 class="mb-[10cqh] text-center font-bold text-4xl">Failed to create lobby</h1>
            <For each={buttons}>
              {(button, index) => (
                <Button
                  gradient="gradient-settings"
                  selected={position() === index()}
                  active={pressed() && position() === index()}
                  onClick={button.action}
                  onMouseEnter={() => set(index())}
                >
                  {button.label}
                </Button>
              )}
            </For>
          </div>
        </Match>
      </Switch>
    </Layout>
  );
}
