// apps/game/src/pages/lobby/[id].tsx
import { Navigate, useNavigate, useParams } from "@solidjs/router";
import { createMutation, createQuery, useQueryClient } from "@tanstack/solid-query";
import { Match, Switch, createSignal } from "solid-js";
import KeyHints from "~/components/key-hints";
import Layout from "~/components/layout";
import TitleBar from "~/components/title-bar";
import Button from "~/components/ui/button";
import { useNavigation } from "~/hooks/navigation";
import { v1 } from "~/lib/api";
import { lobbyQueryOptions } from "~/lib/queries";

export default function LobbyUserPage() {
  const { id } = useParams<{ id: string }>();
  const [pressed, setPressed] = createSignal(false);
  const navigate = useNavigate();
  const onBack = () => navigate("/lobby");
  const queryClient = useQueryClient();

  const lobbyQuery = createQuery(() => lobbyQueryOptions());
  const user = () => lobbyQuery.data?.users.find((user) => user.id === Number.parseInt(id));

  const kickUserMutation = createMutation(() => ({
    mutationFn: async () => {
      const u = user();

      if (!u) {
        return;
      }
      await v1.lobbies.current.kick[":userId"].post({
        params: { userId: u.id.toString() },
      });
    },
    onSuccess: async () => {
      await queryClient.invalidateQueries(lobbyQueryOptions());
      navigate("/lobby");
    },
  }));

  useNavigation(() => ({
    layer: 0,
    onKeydown(event) {
      if (event.action === "back") {
        onBack();
      } else if (event.action === "confirm") {
        setPressed(true);
      }
    },
    onKeyup(event) {
      if (event.action === "confirm") {
        setPressed(false);
        kickUserMutation.mutate();
      }
    },
  }));

  return (
    <Layout
      intent="secondary"
      header={<TitleBar title="Lobby" description={user()?.username || "?"} onBack={onBack} />}
      footer={<KeyHints hints={["back", "navigate", "confirm"]} />}
    >
      <Switch>
        <Match when={user()}>
          <div class="flex w-full flex-grow flex-col justify-center">
            <Button
              selected
              gradient="gradient-lobby"
              onClick={() => kickUserMutation.mutate()}
              loading={kickUserMutation.isPending}
              active={pressed()}
            >
              Kick
            </Button>
          </div>
        </Match>
        <Match when={!lobbyQuery.isPending && !user()}>
          <Navigate href="/lobby" />
        </Match>
      </Switch>
    </Layout>
  );
}

// apps/tauri/src/pages/lobby/[id].vue
<script setup lang="ts">
import type { MenuNavigationEvent } from '~/composables/useMenuNavigation'

const router = useRouter()
const route = useRoute('/lobby/[id]')
const { client } = useTRPC()

const back = () => {
  router.push({ name: '/lobby/' })
}

const kickUser = async () => {
  const id = route.params.id
  await client.lobby.kick.mutate({ userId: id })
}

const kickFallback = useOfflineFallbackFn(kickUser, async () => {})

const { isLoading, mutate } = useMutation({
  mutationFn: kickFallback,
  retry: 4,
  retryDelay: 1000,
  onSuccess: () => {
    back()
  },
})

const queryUsers = async () => {
  const lobbyStatus = await client.lobby.status.query()
  return lobbyStatus.lobby.users
}

const fallback = useOfflineFallbackFn(queryUsers, async () => [])

const status = useQuery({
  queryKey: ['queryStatus'],
  queryFn: fallback,
  retry: 2,
  retryDelay: 0,
  refetchOnWindowFocus: false,
})

const username = computed(() => {
  const id = route.params.id as string
  const user = status?.data?.value?.find(user => user.id === id)
  return user?.username
})

useMenuNavigation(useRepeatThrottleFn(e => onNavigate(e), 150))
const onNavigate = (event: MenuNavigationEvent) => {
  if (event.action === 'back') {
    back()
  } else if (event.action === 'confirm') {
    kick()
  }
}
const kick = () => {
  if (isLoading.value) return
  mutate()
}

const confirm = useSoundEffect('confirm')

onBeforeUnmount(() => {
  confirm.play()
})
</script>

<template>
  <Layout class="gradient-bg-secondary" @back="back">
    <template #header>
      <TitleBar title="Lobby" :description="username" @back="back" />
    </template>
    <div class="flex flex-col justify-center">
      <WideButton
        label="Kick"
        :gradient="{ start: '#36D1DC', end: '#5B86E5' }"
        :active="true"
        @click="kick"
      />
    </div>
    <template #footer>
      <KeyHints :hints="['back', 'confirm']" />
    </template>
  </Layout>
</template>
