// apps/tauri/src/components/game/Lyrics.vue
<script setup lang="ts">
import LyricsNote from './LyricsNote.vue'
import { Note } from '~/logic/song/note'
import type { Sentence } from '~/logic/song/sentence'
import type { LocalSong } from '~/logic/song/song'
import { millisecondInSongToBeatWithoutGap } from '~/logic/utils/bpm.utils'
import type { Microphone } from '~/stores/settings'

const props = defineProps<{
  song: LocalSong
  sentence?: Sentence
  nextSentence?: Sentence
  microphone: Microphone
  position: 'top' | 'bottom'
}>()

const lyricsNoteEls = useTemplateRefsList<InstanceType<typeof LyricsNote>>()
const emptyNote = ref(new Note('Normal', 0, 0, 0, ' '))
const nextSentence = computed(() => {
  const notes = props.nextSentence?.notes.map((note) => {
    return { text: note.text, italic: note.type === 'Freestyle' }
  })
  if (!notes) return [{ text: ' ', italic: false }]
  return notes
})

const leadInStartPercentage = ref(0)
const leadInEndPercentage = ref(0)

const calculateLeadIn = (beat: number) => {
  if (props.sentence) {
    const percentage = ((beat - props.sentence.minBeat) * -100) / millisecondInSongToBeatWithoutGap(props.song, 3000)
    leadInEndPercentage.value = percentage
    leadInStartPercentage.value = percentage + 30
  }
}

const update = (beat: number) => {
  for (const el of lyricsNoteEls.value) {
    el.update(beat)
  }
  calculateLeadIn(beat)
}

defineExpose({
  update,
})
</script>

<template>
  <div class="w-full bg-black/70" :class="[props.position === 'top' ? 'pt-1.2cqh pb-0.8cqh' : 'pb-1.8cqh']">
    <div class="flex w-full">
      <div class="flex-grow pt-0.8cqw pb-0.6cqw pr-0.3cqw">
        <div v-if="props.sentence" class="lead-in h-full" />
      </div>
      <template v-if="props.sentence">
        <LyricsNote
          v-for="note in props.sentence.notes"
          :key="note.startBeat"
          :ref="lyricsNoteEls.set"
          :note="note"
          :microphone="props.microphone"
        />
      </template>
      <LyricsNote v-else :ref="lyricsNoteEls.set" :note="emptyNote" :microphone="props.microphone" />
      <div class="flex-grow" />
    </div>
    <div class="text-white/50 text-center text-1.7cqw -mt-0.5cqw">
      <span
        v-for="(note, index) in nextSentence"
        :key="index"
        class="whitespace-pre-wrap"
        :class="[note.italic ? 'italic' : '']"
      >
        {{ note.text }}
      </span>
    </div>
  </div>
</template>

<style scoped>
.lead-in {
  background: linear-gradient(
    270deg,
    rgba(0, 0, 0, 0) v-bind('`${leadInEndPercentage}%`'),
    v-bind('props.microphone.color') v-bind('`${leadInEndPercentage}%`'),
    rgba(0, 0, 0, 0) v-bind('`${leadInStartPercentage}%`')
  );
}
</style>

// apps/game/src/components/game/lyrics.tsx
import { Key } from "@solid-primitives/keyed";
import { For, Show, createMemo } from "solid-js";
import { useGame } from "~/lib/game/game";
import { usePlayer } from "~/lib/game/player";
import { msToBeatWithoutGap } from "~/lib/ultrastar/bpm";
import type { Note } from "~/lib/ultrastar/note";
import { clamp } from "~/lib/utils/math";

export default function Lyrics() {
  const game = useGame();
  const player = usePlayer();

  const leadInPercentage = createMemo(() => {
    const phrase = player.phrase();
    const song = game.song();
    if (!phrase || !song || !game.started()) {
      return;
    }

    const beat = game.beat();
    const startBeat = phrase.notes[0]?.startBeat;

    if (startBeat === undefined) {
      return;
    }

    const percentage = ((beat - startBeat) * -100) / msToBeatWithoutGap(song, 3000);

    return {
      end: percentage,
      start: percentage + 30,
    };
  });

  const micColor = () => `var(--color-${player.microphone().color}-500)`;

  return (
    <div
      class="w-full bg-black/70 transition-opacity duration-500"
      classList={{
        "opacity-0": !player.phrase(),
        "rounded-b-xl pt-[1.2cqh] pb-[0.8cqh]": player.index() === 0,
        "rounded-t-xl pb-[1.8cqh]": player.index() === 1,
      }}
    >
      <div class="grid grid-cols-[1fr_max-content_1fr]">
        <div class="pt-3 pr-1 pb-2">
          <Show when={leadInPercentage()}>
            {(percentage) => (
              <div
                style={{
                  "background-image": `linear-gradient(270deg, transparent ${percentage().end}%, ${micColor()} ${
                    percentage().end
                  }%, transparent ${percentage().start}%`,
                }}
                class="h-full w-full"
              />
            )}
          </Show>
        </div>
        <div>
          <Key
            fallback={<span class="text-4xl text-transparent leading-relaxed">{"\u00A0"}</span>}
            each={player.phrase()?.notes}
            by={(note) => note.startBeat}
          >
            {(note) => <LyricsNote note={note()} micColor={micColor()} />}
          </Key>
        </div>
        <div />
      </div>
      <div class="text-center text-3xl text-white/50">
        <For fallback={<span class="text-transparent">{"\u00A0"}</span>} each={player.nextPhrase()?.notes}>
          {(note) => (
            <span
              class="whitespace-nowrap"
              classList={{
                italic: note.type === "Freestyle",
              }}
            >
              {note.text}
            </span>
          )}
        </For>
      </div>
    </div>
  );
}

interface LyricsNoteProps {
  note: Note;
  micColor: string;
}
function LyricsNote(props: LyricsNoteProps) {
  const game = useGame();

  const percentage = createMemo(() => {
    const beat = game.beat();

    if (beat < props.note.startBeat) {
      return 0;
    }

    return clamp(((beat - props.note.startBeat) * 100) / props.note.length, 0, 100);
  });

  return (
    <span
      style={{
        "background-image": `linear-gradient(to right, ${props.micColor} ${percentage()}%, white ${percentage()}%)`,
      }}
      class="inline-block whitespace-pre bg-clip-text text-4xl text-transparent leading-relaxed"
      classList={{
        "m-[-0.15cqw] p-[0.15cqw] italic": props.note.type === "Freestyle",
      }}
    >
      {props.note.text}
    </span>
  );
}
