// apps/game/src/routes/settings/songs/[path].tsx
import { useNavigate, useParams } from "@solidjs/router";
import { createSignal } from "solid-js";
import KeyHints from "~/components/key-hints";
import Layout from "~/components/layout";
import TitleBar from "~/components/title-bar";
import Button from "~/components/ui/button";
import { useNavigation } from "~/hooks/navigation";
import { songsStore } from "~/stores/songs";

export default function SongPathSettings() {
  const navigate = useNavigate();
  const [pressed, setPressed] = createSignal(false);

  const onBack = () => navigate("/settings/songs");

  const params = useParams<{ path: string }>();
  const path = () => decodeURIComponent(params.path);

  const removePath = () => {
    songsStore.removeSongPath(path());
    onBack();
  };

  useNavigation(() => ({
    layer: 0,
    onKeydown(event) {
      if (event.action === "back") {
        onBack();
      } else if (event.action === "confirm") {
        setPressed(true);
      }
    },
    onKeyup(event) {
      if (event.action === "confirm") {
        setPressed(false);
        removePath();
      }
    },
  }));

  return (
    <Layout
      intent="secondary"
      header={<TitleBar title="Settings" description={`Songs / ${path()}`} onBack={onBack} />}
      footer={<KeyHints hints={["back", "navigate", "confirm"]} />}
    >
      <div class="flex w-full flex-grow flex-col justify-center">
        <Button
          selected
          gradient="gradient-settings"
          onClick={() => {
            removePath();
            onBack();
          }}
          active={pressed()}
        >
          Remove
        </Button>
      </div>
    </Layout>
  );
}

// apps/tauri/src/pages/settings/songs/local/[path].vue
<script setup lang="ts">
const router = useRouter()
const confirm = useSoundEffect('confirm')
const route = useRoute('/settings/songs/local/[path]')
const songsStore = useSongsStore()
const { t } = useI18n()

const back = () => {
  router.push({ name: '/settings/songs/' })
}

const deletePath = () => {
  songsStore.removeLocalPath(route.params.path)
  back()
}

useMenuNavigation((e) => {
  if (e.action === 'confirm') {
    deletePath()
  } else if (e.action === 'back') {
    back()
  }
})

onBeforeUnmount(() => {
  confirm.play()
})
</script>

<template>
  <Layout class="gradient-bg-secondary" @back="back">
    <template #header>
      <TitleBar title="Settings" :description="`${t('settings.songs.title')} / ${route.params.path}`" @back="back" />
    </template>
    <div class="flex flex-col gap-0.5cqh">
      <WideButton class="from-settings-start to-settings-end" :active="true" @click="deletePath">
        {{ t('settings.songs.remove') }}
      </WideButton>
    </div>
    <template #footer>
      <KeyHints :hints="['back', 'navigate', 'confirm']" />
    </template>
  </Layout>
</template>
