// apps/game/src/components/title-bar.tsx
import { Show } from "solid-js";
import IconChevronLeft from "~icons/lucide/chevron-left";

interface TitleBarProps {
  title: string;
  description?: string;
  onBack?: () => void;
}

export default function TitleBar(props: TitleBarProps) {
  return (
    <div class="flex items-center gap-0.5cqw font-semibold text-base uppercase">
      <Show when={props.onBack}>
        <button class="flex items-center gap-0.5cqw" onClick={props.onBack} type="button">
          <IconChevronLeft />
        </button>
      </Show>
      <div>
        {props.title}
        <Show when={props.description}>
          <span class="pl-2 text-xs">/ {props.description}</span>
        </Show>
      </div>
    </div>
  );
}

// apps/electron/src/renderer/src/components/menu/TitleBar.vue
<script setup lang="ts">
const props = withDefaults(
  defineProps<{
    title: string
    description?: string
    backArrow?: boolean
  }>(),
  {
    backArrow: true,
  },
)

const emit = defineEmits<{
  (e: 'back'): void
}>()
</script>

<template>
  <div class="flex flex-row items-center gap-0.5cqw text-neutral-400 font-semibold uppercase">
    <Icon icon="ChevronLeft" role="button" class="text-2cqw" @click="emit('back')" />
    <div class="text-1.3cqw -mt-0.15cqw">
      {{ props.title }}
    </div>
    <div v-if="props.description" class="text-0.8cqw">
      / {{ props.description }}
    </div>
  </div>
</template>
