// apps/game/src/pages/settings/volume/index.tsx
import { useNavigate } from "@solidjs/router";
import { For, createSignal } from "solid-js";
import KeyHints from "~/components/key-hints";
import Layout from "~/components/layout";
import TitleBar from "~/components/title-bar";
import Button from "~/components/ui/button";
import Slider from "~/components/ui/slider";
import { createLoop } from "~/hooks/loop";
import { useNavigation } from "~/hooks/navigation";
import { settingsStore } from "~/stores/settings";

export default function VolumeSettings() {
  const [pressed, setPressed] = createSignal(false);
  const navigate = useNavigate();
  const onBack = () => {
    navigate("/settings");
  };

  const [volume, setVolume] = createSignal(settingsStore.volume());

  const saveVolume = () => {
    settingsStore.saveVolume(volume());
    onBack();
  };

  const inputs = [
    {
      type: "slider" as const,
      label: "Master Volume",
      value: () => Math.round(volume().master * 100),
      min: 0,
      max: 100,
      step: 1,
      onInput: (value: number) => {
        setVolume((prev) => ({ ...prev, master: Math.round(value) / 100 }));
      },
    },
    {
      type: "slider" as const,
      label: "Game Volume",
      value: () => Math.round(volume().game * 100),
      min: 0,
      max: 100,
      step: 1,
      onInput: (value: number) => {
        setVolume((prev) => ({ ...prev, game: Math.round(value) / 100 }));
      },
    },
    {
      type: "slider" as const,
      label: "Preview Volume",
      value: () => Math.round(volume().preview * 100),
      min: 0,
      max: 100,
      step: 1,
      onInput: (value: number) => {
        setVolume((prev) => ({ ...prev, preview: Math.round(value) / 100 }));
      },
    },
    {
      type: "slider" as const,
      label: "Menu Volume",
      value: () => Math.round(volume().menu * 100),
      min: 0,
      max: 100,
      step: 1,
      onInput: (value: number) => {
        setVolume((prev) => ({ ...prev, menu: Math.round(value) / 100 }));
      },
    },
    {
      type: "button" as const,
      label: "Save",
      action: saveVolume,
    },
  ];

  const { position, increment, decrement, set } = createLoop(() => inputs.length);

  useNavigation(() => ({
    layer: 0,
    onKeydown(event) {
      if (event.action === "back") {
        onBack();
      } else if (event.action === "up") {
        decrement();
      } else if (event.action === "down") {
        increment();
      } else if (event.action === "confirm") {
        setPressed(true);
      }
    },
    onKeyup(event) {
      if (event.action === "confirm") {
        setPressed(false);
        const input = inputs[position()];
        if (input?.type === "button") {
          input.action();
        }
      }
    },
  }));

  return (
    <Layout
      intent="secondary"
      header={<TitleBar title="Settings" description="Volume" onBack={onBack} />}
      footer={<KeyHints hints={["back", "navigate", "confirm"]} />}
    >
      <div class="flex w-full flex-grow flex-col justify-center">
        <For each={inputs}>
          {(input, index) => {
            if (input.type === "slider") {
              return (
                <Slider
                  selected={position() === index()}
                  gradient="gradient-settings"
                  onMouseEnter={() => set(index())}
                  {...input}
                  value={input.value()}
                />
              );
            }
            return (
              <Button
                selected={position() === index()}
                active={pressed() && position() === index()}
                gradient="gradient-settings"
                onClick={input.action}
                onMouseEnter={() => set(index())}
              >
                {input.label}
              </Button>
            );
          }}
        </For>
      </div>
    </Layout>
  );
}

// apps/tauri/src/pages/settings/volume/index.vue
<script setup lang="ts">
import { clamp } from '~/lib/utils/math'

const router = useRouter()
const { t } = useI18n()
const settingsStore = useSettingsStore()
const select = useSoundEffect('select')
const confirm = useSoundEffect('confirm')

const back = () => {
  router.push({ name: '/settings/' })
}

const sliders = [
  {
    label: t('settings.volume.master'),
    ref: computed({
      get() {
        return settingsStore.volume.master
      },
      set(newValue: number) {
        settingsStore.volume.master = clamp(newValue, 0, 100)
      },
    }),
  },
  {
    label: t('settings.volume.game'),
    ref: computed({
      get() {
        return settingsStore.volume.game
      },
      set(newValue: number) {
        settingsStore.volume.game = clamp(newValue, 0, 100)
      },
    }),
  },
  {
    label: t('settings.volume.preview'),
    ref: computed({
      get() {
        return settingsStore.volume.preview
      },
      set(newValue: number) {
        settingsStore.volume.preview = clamp(newValue, 0, 100)
      },
    }),
  },
  {
    label: t('settings.volume.menu'),
    ref: computed({
      get() {
        return settingsStore.volume.menu
      },
      set(newValue: number) {
        settingsStore.volume.menu = clamp(newValue, 0, 100)
      },
    }),
  },
]

const { position, increment, decrement } = useLoop(sliders.length - 1)

useMenuNavigation((e) => {
  if (e.action === 'down') {
    increment()
  } else if (e.action === 'up') {
    decrement()
  } else if (e.action === 'back') {
    back()
  } else if (e.action === 'left') {
    const slider = sliders.at(position.value)
    if (slider) {
      slider.ref.value -= 5
    }
  } else if (e.action === 'right') {
    const slider = sliders.at(position.value)
    if (slider) {
      slider.ref.value += 5
    }
  }
})

watch(position, () => select.play())

onBeforeUnmount(() => {
  confirm.play()
})
</script>

<template>
  <Layout class="gradient-bg-secondary" @back="back">
    <template #header>
      <TitleBar :title="t('settings.title')" :description="t('settings.volume.title')" @back="back" />
    </template>
    <div class="flex flex-col gap-0.5cqh">
      <WideSlider
        v-for="(slider, i) in sliders"
        :key="slider.label"
        v-model="slider.ref.value"
        :label="slider.label"
        class="from-settings-start to-settings-end"
        :active="position === i"
        :click-step="5"
        @mouseenter="() => (position = i)"
      ></WideSlider>
    </div>
    <template #footer>
      <KeyHints :hints="['back', 'navigate', 'confirm']" />
    </template>
  </Layout>
</template>

<style scoped></style>
