// apps/game/src/components/key-hints.tsx
import { For, type JSX, Match, Switch } from "solid-js";

import IconDownArrowKey from "~icons/sing/down-arrow-key";
import IconEnterKey from "~icons/sing/enter-key";
import IconEscKey from "~icons/sing/esc-key";
import IconLeftArrowKey from "~icons/sing/left-arrow-key";
import IconRightArrowKey from "~icons/sing/right-arrow-key";
import IconUpArrowKey from "~icons/sing/up-arrow-key";

type HintType = "navigate" | "confirm" | "back";

interface KeyHintsProps {
  hints: HintType[];
}

export default function KeyHints(props: KeyHintsProps) {
  return (
    <div class="flex items-center gap-8">
      <For each={props.hints}>
        {(hint) => (
          <Switch>
            <Match when={hint === "back"}>
              <KeyHint label="Back" icon={<IconEscKey />} />
            </Match>
            <Match when={hint === "confirm"}>
              <KeyHint label="Confirm" icon={<IconEnterKey />} />
            </Match>
            <Match when={hint === "navigate"}>
              <KeyHint
                label="Navigate"
                icon={
                  <div class="flex flex-col items-center text-0.6cqw">
                    <IconUpArrowKey />
                    <div class="flex">
                      <IconLeftArrowKey />
                      <IconDownArrowKey />
                      <IconRightArrowKey />
                    </div>
                  </div>
                }
              />
            </Match>
          </Switch>
        )}
      </For>
    </div>
  );
}

interface KeyHintProps {
  label: string;
  icon: JSX.Element;
}
function KeyHint(props: KeyHintProps) {
  return (
    <div class="flex items-center gap-0.5cqw">
      {props.icon} {props.label}
    </div>
  );
}

// apps/tauri/src/components/KeyHints.vue
<script setup lang="ts">
import { keyMode } from '~/lib/ui/keys'

type HintType = 'navigate' | 'confirm' | 'back'
const props = defineProps<{
  hints: HintType[]
}>()

const { t } = useI18n()

const keyboardHintMap = new Map<HintType, { text: string; class: string }>([
  ['navigate', { text: t('key_hint.navigate'), class: 'i-sing-key-arrows text-1.5cqw' }],
  ['confirm', { text: t('key_hint.confirm'), class: 'i-sing-key-enter' }],
  ['back', { text: t('key_hint.back'), class: 'i-sing-key-escape text-1.4cqw' }],
])

const gamepadHintMap = new Map<HintType, { text: string; class: string }>([
  ['navigate', { text: t('key_hint.navigate'), class: 'i-sing-xbox-cross' }],
  ['confirm', { text: t('key_hint.confirm'), class: 'i-sing-xbox-a' }],
  ['back', { text: t('key_hint.back'), class: 'i-sing-xbox-b' }],
])

const hints = computed(() => {
  return props.hints.map((hint) => {
    return keyMode.value === 'keyboard' ? keyboardHintMap.get(hint) : gamepadHintMap.get(hint)
  })
})
</script>

<template>
  <div class="flex gap-1.2cqw text-1.2cqw text-neutral-400">
    <div v-for="hint in hints" :key="hint.text" class="flex items-center gap-0.5cqw">
      <div :class="hint.class"></div>
      <div>
        {{ hint.text }}
      </div>
    </div>
  </div>
</template>
