// apps/game/src/pages/lobby/index.tsx
import { useNavigate } from "@solidjs/router";
import { createQuery } from "@tanstack/solid-query";
import { For, createSignal } from "solid-js";
import KeyHints from "~/components/key-hints";
import Layout from "~/components/layout";
import TitleBar from "~/components/title-bar";
import Avatar from "~/components/ui/avatar";
import Button from "~/components/ui/button";
import { createLoop } from "~/hooks/loop";
import { useNavigation } from "~/hooks/navigation";
import { lobbyQueryOptions } from "~/lib/queries";

export default function LobbyPage() {
  const [pressed, setPressed] = createSignal(false);

  const navigate = useNavigate();
  const onBack = () => navigate("/home");

  const lobbyQuery = createQuery(() => lobbyQueryOptions());

  const { position, increment, decrement, set } = createLoop(() => lobbyQuery.data?.users.length ?? 0);

  useNavigation(() => ({
    layer: 0,
    onKeydown(event) {
      if (event.action === "up") {
        decrement();
      } else if (event.action === "down") {
        increment();
      } else if (event.action === "confirm") {
        setPressed(true);
      } else if (event.action === "back") {
        onBack();
      }
    },
    onKeyup(event) {
      if (event.action === "confirm") {
        setPressed(false);
        const user = lobbyQuery.data?.users[position()];
        if (user) {
          navigate(`/lobby/${user.id}`);
        }
      }
    },
  }));

  return (
    <Layout
      intent="secondary"
      header={<TitleBar title="Lobby" onBack={onBack} />}
      footer={<KeyHints hints={["back", "navigate", "confirm"]} />}
    >
      <div class="flex w-full flex-grow flex-col justify-center">
        <For each={lobbyQuery.data?.users}>
          {(user, index) => (
            <Button
              gradient="gradient-lobby"
              selected={position() === index()}
              active={pressed() && position() === index()}
              onClick={() => navigate(`/lobby/${user.id}`)}
              onMouseEnter={() => set(index())}
            >
              <Avatar user={user} />
              <span>{user.username}</span>
            </Button>
          )}
        </For>
      </div>
    </Layout>
  );
}

// apps/electron/src/renderer/src/pages/lobby/index.vue
<script setup lang="ts">
import type { MenuNavigationEvent } from '@renderer/composables/useMenuNavigation'
import type { User } from '@renderer/logic/types'

const router = useRouter()
const { client } = useTRPC()

const back = () => {
  router.push('/home')
}

const queryUsers = async () => {
  const lobbyStatus = await client.lobby.status.query()
  return lobbyStatus.lobby.users
}

const fallback = useOfflineFallbackFn(queryUsers, async () => [])

const status = useQuery({
  queryKey: ['queryStatus'],
  queryFn: fallback,
  retry: 2,
  retryDelay: 0,
  refetchOnWindowFocus: false,
  cacheTime: 10000, // 10 seconds
  refetchInterval: 10000, // 10 seconds
})

const users = computed(() => status?.data?.value || [])

const maxPosition = computed(() => {
  const length = status?.data?.value?.length || 1
  return length - 1
})

const { position, increment, decrement } = useLoop(maxPosition)

useMenuNavigation(useRepeatThrottleFn(e => onNavigate(e), 150))
const onNavigate = (event: MenuNavigationEvent) => {
  if (event.action === 'back') {
    router.back()
  } else if (event.action === 'confirm') {
    const user = users.value.at(position.value)
    if (user) {
      toDetails(user)
    }
  } else if (event.action === 'down') {
    increment()
  } else if (event.action === 'up') {
    decrement()
  }
}

const toDetails = (user: User) => {
  router.push(`/lobby/${user.id}`)
}
</script>

<template>
  <Layout class="gradient-bg-secondary" @back="back">
    <template #header>
      <TitleBar title="Lobby" @back="back" />
    </template>
    <div class="flex flex-col justify-center">
      <WideButton
        v-for="(user, i) in users"
        :key="user.username"
        :label="user.username"
        :gradient="{ start: '#36D1DC', end: '#5B86E5' }"
        :active="position === i"
        @mouseenter="() => (position = i)"
        @click="() => toDetails(user)"
      />
    </div>
    <template #footer>
      <KeyHints :hints="['back', 'navigate', 'confirm']" />
    </template>
  </Layout>
</template>
