// apps/tauri/src/pages/settings/credits/index.vue
<script setup lang="ts">
import { open } from '@tauri-apps/api/shell'
import type { MenuNavigationEvent } from '~/composables/useMenuNavigation'

const router = useRouter()

const back = () => {
  router.push({ name: '/settings/' })
}

const buttons = [
  { label: 'UltraStar Play ', action: () => open('https://github.com/UltraStar-Deluxe/Play/') },
  { label: 'Karol Szcześniak', action: () => undefined },
]

const { position, increment, decrement } = useLoop(buttons.length - 1)

useMenuNavigation(useRepeatThrottleFn((e) => onNavigate(e), 150))
const onNavigate = (event: MenuNavigationEvent) => {
  if (event.action === 'back') {
    back()
  } else if (event.action === 'confirm') {
    buttons.at(position.value)?.action()
  } else if (event.action === 'down') {
    increment()
  } else if (event.action === 'up') {
    decrement()
  }
}

const select = useSoundEffect('select')
watch(position, () => select.play())

const confirm = useSoundEffect('confirm')

onBeforeUnmount(() => {
  confirm.play()
})
</script>

<template>
  <Layout class="gradient-bg-secondary" @back="back">
    <template #header>
      <TitleBar title="Settings" description="Credits" @back="back" />
    </template>
    <div>
      <WideButton
        v-for="(button, i) in buttons"
        :key="button.label"
        :label="button.label"
        :gradient="{ start: '#36D1DC', end: '#5B86E5' }"
        :active="position === i"
        @mouseenter="() => (position = i)"
        @click="button.action"
      />
    </div>
    <template #footer>
      <KeyHints :hints="['back', 'navigate', 'confirm']" />
    </template>
  </Layout>
</template>

// apps/game/src/pages/settings/credits.tsx
import { useNavigate } from "@solidjs/router";
import { open } from "@tauri-apps/plugin-shell";
import { For, createSignal } from "solid-js";
import KeyHints from "~/components/key-hints";
import Layout from "~/components/layout";
import TitleBar from "~/components/title-bar";
import Button from "~/components/ui/button";
import { createLoop } from "~/hooks/loop";
import { useNavigation } from "~/hooks/navigation";

export default function CreditsPage() {
  const navigate = useNavigate();
  const [pressed, setPressed] = createSignal(false);

  const onBack = () => navigate("/settings");
  const buttons = [
    {
      label: "UltraStar Play",
      action: () => open("https://ultrastar-play.com"),
    },
    {
      label: "Karol Szcześniak",
    },
  ];

  const { position, increment, decrement, set } = createLoop(buttons.length);

  useNavigation(() => ({
    layer: 0,
    onKeydown(event) {
      if (event.action === "back") {
        onBack();
      } else if (event.action === "up") {
        decrement();
      } else if (event.action === "down") {
        increment();
      } else if (event.action === "confirm") {
        setPressed(true);
      }
    },
    onKeyup(event) {
      if (event.action === "confirm") {
        setPressed(false);
        buttons[position()]?.action?.();
      }
    },
  }));

  return (
    <Layout
      intent="secondary"
      header={<TitleBar title="Settings" onBack={onBack} />}
      footer={<KeyHints hints={["back", "navigate", "confirm"]} />}
    >
      <div class="flex w-full flex-grow flex-col justify-center">
        <For each={buttons}>
          {(button, index) => (
            <Button
              gradient="gradient-settings"
              selected={position() === index()}
              active={pressed() && position() === index()}
              onClick={button.action}
              onMouseEnter={() => set(index())}
            >
              {button.label}
            </Button>
          )}
        </For>
      </div>
    </Layout>
  );
}
