// apps/tauri/src/pages/settings/index.vue
<script setup lang="ts">
const router = useRouter()
const select = useSoundEffect('select')
const confirm = useSoundEffect('confirm')
const { t } = useI18n()

const back = () => {
  router.push({ name: '/home' })
}

const buttons = [
  { label: 'Volume', action: () => router.push({ name: '/settings/volume/' }) },
  { label: 'Microphones', action: () => router.push({ name: '/settings/microphones/' }) },
  { label: 'Songs', action: () => router.push({ name: '/settings/songs/' }) },
  { label: 'Credits', action: () => router.push({ name: '/settings/credits/' }) },
]

const { position, increment, decrement } = useLoop(buttons.length - 1)

useMenuNavigation((e) => {
  if (e.action === 'confirm') {
    buttons.at(position.value)?.action()
  } else if (e.action === 'down') {
    increment()
  } else if (e.action === 'up') {
    decrement()
  } else if (e.action === 'back') {
    back()
  }
})

watch(position, () => select.play())

onBeforeUnmount(() => {
  confirm.play()
})
</script>

<template>
  <Layout class="gradient-bg-secondary" @back="back">
    <template #header>
      <TitleBar :title="t('settings.title')" @back="back" />
    </template>
    <div class="flex flex-col gap-0.5cqh">
      <WideButton
        v-for="(button, i) in buttons"
        :key="button.label"
        class="from-settings-start to-settings-end"
        :active="position === i"
        @mouseenter="() => (position = i)"
        @click="button.action"
      >
        {{ button.label }}
      </WideButton>
    </div>
    <template #footer>
      <KeyHints :hints="['back', 'navigate', 'confirm']" />
    </template>
  </Layout>
</template>

// apps/game/src/pages/settings/index.tsx
import { useNavigate } from "@solidjs/router";
import { For, createSignal } from "solid-js";
import KeyHints from "~/components/key-hints";
import Layout from "~/components/layout";
import TitleBar from "~/components/title-bar";
import Button from "~/components/ui/button";
import { createLoop } from "~/hooks/loop";
import { useNavigation } from "~/hooks/navigation";

export default function Settings() {
  const navigate = useNavigate();
  const [pressed, setPressed] = createSignal(false);

  const onBack = () => navigate("/home");
  const buttons = [
    {
      label: "Songs",
      action: () => navigate("/settings/songs"),
    },
    {
      label: "Microphones",
      action: () => navigate("/settings/microphones"),
    },
    {
      label: "Volume",
      action: () => navigate("/settings/volume"),
    },
    {
      label: "Credits",
      action: () => navigate("/settings/credits"),
    },
  ];

  const { position, increment, decrement, set } = createLoop(buttons.length);

  useNavigation(() => ({
    layer: 0,
    onKeydown(event) {
      if (event.action === "back") {
        onBack();
      } else if (event.action === "up") {
        decrement();
      } else if (event.action === "down") {
        increment();
      } else if (event.action === "confirm") {
        setPressed(true);
      }
    },
    onKeyup(event) {
      if (event.action === "confirm") {
        setPressed(false);
        buttons[position()]?.action();
      }
    },
  }));

  return (
    <Layout
      intent="secondary"
      header={<TitleBar title="Settings" onBack={onBack} />}
      footer={<KeyHints hints={["back", "navigate", "confirm"]} />}
    >
      <div class="flex w-full flex-grow flex-col justify-center">
        <For each={buttons}>
          {(button, index) => (
            <Button
              gradient="gradient-settings"
              selected={position() === index()}
              active={pressed() && position() === index()}
              onClick={button.action}
              onMouseEnter={() => set(index())}
            >
              {button.label}
            </Button>
          )}
        </For>
      </div>
    </Layout>
  );
}
