// apps/tauri/src/pages/settings/microphones/index.vue
<script setup lang="ts">
import type { MenuNavigationEvent } from '~/composables/useMenuNavigation'

const router = useRouter()
const settingsStore = useSettingsStore()

const back = () => {
  router.push({ name: '/settings/' })
}

const maxPosition = computed(() => {
  const length = settingsStore.microphones.length
  if (length >= 2) {
    return length - 1
  }
  return length
})

const { position, increment, decrement } = useLoop(maxPosition)

useMenuNavigation(useRepeatThrottleFn(e => onNavigate(e), 150))

const onNavigate = (event: MenuNavigationEvent) => {
  if (event.action === 'back') {
    back()
  } else if (event.action === 'confirm') {
    toPath(position.value)
  } else if (event.action === 'left') {
    decrement()
  } else if (event.action === 'right') {
    increment()
  }
}

const toPath = (index: number) => {
  router.push({ name: '/settings/microphones/[id]', params: { id: index } })
}

const gradient = { start: '#36D1DC', end: '#5B86E5' }

const select = useSoundEffect('select')
watch(position, () => select.play())

const confirm = useSoundEffect('confirm')

onBeforeUnmount(() => {
  confirm.play()
})
</script>

<template>
  <Layout class="gradient-bg-secondary" @back="back">
    <template #header>
      <TitleBar title="Settings" description="Microphones" @back="back" />
    </template>
    <div class="flex flex justify-center items-center gap-1cqw">
      <IconButton
        v-for="microphone, index in settingsStore.microphones"
        :key="microphone.name + microphone.channel"
        :active="index === position"
        :label="microphone.name"
        icon="Folder"
        :gradient="gradient"
        class="w-1/11"
        @mouseenter="() => (position = index)"
        @click="toPath(index)"
      />
      <IconButton
        v-if="settingsStore.microphones.length < 2"
        :active="position === maxPosition"
        label="Add"
        icon="Plus"
        :gradient="gradient"
        class="w-1/11"
        @mouseenter="() => (position = maxPosition)"
        @click="toPath(maxPosition)"
      />
    </div>
    <template #footer>
      <KeyHints :hints="['back', 'navigate', 'confirm']" />
    </template>
  </Layout>
</template>

// apps/game/src/pages/settings/microphones/index.tsx
import { useNavigate } from "@solidjs/router";
import { type Component, For, createMemo, createSignal } from "solid-js";
import KeyHints from "~/components/key-hints";
import Layout from "~/components/layout";
import TitleBar from "~/components/title-bar";
import IconButton from "~/components/ui/icon-button";
import { createLoop } from "~/hooks/loop";
import { useNavigation } from "~/hooks/navigation";
import { settingsStore } from "~/stores/settings";
import IconMicVocal from "~icons/lucide/mic-vocal";
import IconPlus from "~icons/lucide/plus";

export default function MicrophonesSettings() {
  const [pressed, setPressed] = createSignal(false);

  const navigate = useNavigate();
  const onBack = () => {
    navigate("/settings");
  };

  const buttons = createMemo(() => {
    const buttons: {
      label: string;
      icon: Component<{ class?: string }>;
      action?: () => void;
    }[] = [];

    for (const [index, microphone] of settingsStore.microphones().entries()) {
      buttons.push({
        label: microphone.name,
        icon: IconMicVocal,
        action: () => {
          navigate(`/settings/microphones/${index}`);
        },
      });
    }

    buttons.push({
      label: "Add",
      icon: IconPlus,
      action: () => {
        navigate(`/settings/microphones/${settingsStore.microphones().length}`);
      },
    });

    return buttons;
  });

  const { position, increment, decrement, set } = createLoop(() => buttons().length);

  useNavigation(() => ({
    layer: 0,
    onKeydown(event) {
      if (event.action === "back") {
        onBack();
      } else if (event.action === "left") {
        decrement();
      } else if (event.action === "right") {
        increment();
      } else if (event.action === "confirm") {
        setPressed(true);
      }
    },
    onKeyup(event) {
      if (event.action === "confirm") {
        setPressed(false);
        const button = buttons()[position()];
        button?.action?.();
      }
    },
  }));

  return (
    <Layout
      intent="secondary"
      header={<TitleBar title="Settings" description="Microphones" onBack={onBack} />}
      footer={<KeyHints hints={["back", "navigate", "confirm"]} />}
    >
      <div class="flex w-full flex-grow items-center justify-center gap-1cqw">
        <For each={buttons()}>
          {(button, index) => (
            <IconButton
              onClick={() => button.action?.()}
              onMouseEnter={() => set(index())}
              selected={position() === index()}
              active={pressed() && position() === index()}
              icon={button.icon}
              label={button.label}
              gradient="gradient-settings"
            />
          )}
        </For>
      </div>
    </Layout>
  );
}
