// apps/app/src/components/avatar.tsx
import { Show, createEffect, createSignal, on } from "solid-js";
import { fallback } from "valibot";

interface AvatarProps {
  src?: string;
  fallback?: string;
}

export default function Avatar(props: AvatarProps) {
  const [error, setError] = createSignal(false);

  createEffect(
    on(
      () => props.src,
      () => {
        setError(false);
      }
    )
  );

  const fallback = () => props.fallback?.at(0) || "?";

  return (
    <div class="grid h-10 w-10">
      <div class="col-start-1 row-start-1 flex h-full w-full items-center justify-center rounded-full bg-night-500">{fallback()}</div>
      <Show when={!error()}>
        <img
          onError={() => setError(true)}
          src={props.src || props.fallback}
          alt={props.fallback || "Avatar"}
          class="col-start-1 row-start-1 block h-full w-full rounded-full"
        />
      </Show>
    </div>
  );
}

// apps/web/components/ui/Avatar.vue
<script setup lang="ts">
const props = defineProps<{
  src?: string | null
  fallback?: string
}>()

const imgUrl = ref<string | undefined>()

watch(
  () => props.src,
  (src) => {
    imgUrl.value = src || undefined
  }
)

onMounted(() => {
  if (props.src) {
    imgUrl.value = props.src
  }
})

const imageEl = ref<HTMLImageElement | null>(null)

const onError = () => {
  imgUrl.value = undefined
}
</script>

<template>
  <div class="w-10 h-10 relative flex overflow-hidden rounded-full">
    <div class="absolute w-full h-full flex items-center justify-center bg-muted">
      <p>{{ props.fallback }}</p>
    </div>
    <img
      v-if="!!imgUrl"
      ref="imageEl"
      class="relative w-full h-full object-cover rounded-full"
      :src="props.src || undefined"
      alt=""
      @error="onError"
    />
  </div>
</template>
