// apps/tauri/src/components/Avatar.vue
<script setup lang="ts">
const props = defineProps<{
  src?: string
  alt?: string
  username?: string
}>()

const error = ref(false)

const onError = () => {
  error.value = true
}

watch(
  () => props.src,
  (src) => {
    // set error to true if no src is provided or if src is empty
    error.value = !src || src === ''
  },
  { immediate: true }
)

const initials = computed(() => {
  if (props.username) {
    return props.username[0].toUpperCase()
  }
  return '?'
})
</script>

<template>
  <img v-if="!error" class="h-2cqw w-2cqw rounded-full" :src="props.src" @error="onError" />
  <div
    v-else
    class="inline-block h-2cqw w-2cqw bg-#2ec468 rounded-full text-white flex items-center justify-center text-1cqw overflow-hidden"
  >
    {{ initials }}
  </div>
</template>

// apps/app/src/components/ui/avatar.tsx
import { Show, createEffect, createSignal, on } from "solid-js";
import { joinURL } from "ufo";

interface AvatarProps {
  user: {
    picture?: string | null;
    username?: string | null;
  };
  class?: string;
}

export default function Avatar(props: AvatarProps) {
  const [error, setError] = createSignal(false);

  createEffect(
    on(
      () => props.user,
      () => {
        setError(false);
      }
    )
  );

  const fallback = () => props.user?.username?.at(0) || "?";

  const pictureUrl = () => {
    if (props.user?.picture?.startsWith("/")) {
      return joinURL(import.meta.env.VITE_API_URL, props.user.picture);
    }

    return props.user?.picture || undefined;
  };

  return (
    <div
      class="grid h-10 w-10"
      classList={{
        [props.class || ""]: !!props.class,
      }}
    >
      <div class="gradient-settings col-start-1 row-start-1 flex h-full w-full items-center justify-center rounded-full bg-gradient-to-tr text-white">
        {fallback()}
      </div>
      <Show when={!error() && props.user?.picture}>
        <img
          onError={() => setError(true)}
          src={pictureUrl()}
          alt={props.user?.username || "Avatar"}
          class="col-start-1 row-start-1 block h-full w-full rounded-full"
        />
      </Show>
    </div>
  );
}
