// apps/electron/src/renderer/src/pages/settings/volume/index.vue
<script setup lang="ts">
import type { MenuNavigationEvent } from '@renderer/composables/useMenuNavigation'
import { clamp } from '@renderer/logic/utils/math.utils'

const router = useRouter()
const settingsStore = useSettingsStore()

const back = () => {
  router.back()
}

const sliders = [
  {
    label: 'Master Volume',
    value: computed(() => settingsStore.volume.master),
    setter: (value: number) => (settingsStore.volume.master = value),
  },
  {
    label: 'Game Volume',
    value: computed(() => settingsStore.volume.game),
    setter: (value: number) => (settingsStore.volume.game = value),
  },

  {
    label: 'Preview Volume',
    value: computed(() => settingsStore.volume.preview),
    setter: (value: number) => (settingsStore.volume.preview = value),
  },
  {
    label: 'Menu Volume',
    value: computed(() => settingsStore.volume.menu),
    setter: (value: number) => (settingsStore.volume.menu = value),
  },
]

const { position, increment, decrement } = useLoop(sliders.length - 1)

useMenuNavigation(useRepeatThrottleFn(e => onNavigate(e), 150))
const onNavigate = (event: MenuNavigationEvent) => {
  if (event.action === 'back') {
    router.back()
  } else if (event.action === 'left' || event.action === 'right') {
    const button = sliders.at(position.value)
    if (button) {
      const newValue = button.value.value + (event.action === 'left' ? -5 : 5)
      button.setter(clamp(newValue, 0, 100))
    }
  } else if (event.action === 'down') {
    increment()
  } else if (event.action === 'up') {
    decrement()
  }
}

const select = useSoundEffect('select')
watch(position, () => select.play())

const confirm = useSoundEffect('confirm')

onBeforeUnmount(() => {
  confirm.play()
})
</script>

<template>
  <Layout class="gradient-bg-secondary" @back="back">
    <template #header>
      <TitleBar title="Settings" description="Volume" @back="back" />
    </template>
    <div class="flex flex-col justify-center">
      <RangeInput
        v-for="(slider, i) in sliders"
        :key="slider.label"
        :model-value="slider.value.value"
        :label="slider.label"
        :gradient="{ start: '#36D1DC', end: '#5B86E5' }"
        :active="position === i"
        :click-step="5"
        @mouseenter="() => (position = i)"
        @update:model-value="slider.setter"
      />
    </div>
    <template #footer>
      <KeyHints :hints="['back', 'navigate']" />
    </template>
  </Layout>
</template>

// apps/game/src/pages/settings/volume/index.tsx
import { useNavigate } from "@solidjs/router";
import { For, createSignal } from "solid-js";
import KeyHints from "~/components/key-hints";
import Layout from "~/components/layout";
import TitleBar from "~/components/title-bar";
import Button from "~/components/ui/button";
import Slider from "~/components/ui/slider";
import { createLoop } from "~/hooks/loop";
import { useNavigation } from "~/hooks/navigation";
import { settingsStore } from "~/stores/settings";

export default function VolumeSettings() {
  const [pressed, setPressed] = createSignal(false);
  const navigate = useNavigate();
  const onBack = () => {
    navigate("/settings");
  };

  const [volume, setVolume] = createSignal(settingsStore.volume());

  const saveVolume = () => {
    settingsStore.saveVolume(volume());
    onBack();
  };

  const inputs = [
    {
      type: "slider" as const,
      label: "Master Volume",
      value: () => Math.round(volume().master * 100),
      min: 0,
      max: 100,
      step: 1,
      onInput: (value: number) => {
        setVolume((prev) => ({ ...prev, master: Math.round(value) / 100 }));
      },
    },
    {
      type: "slider" as const,
      label: "Game Volume",
      value: () => Math.round(volume().game * 100),
      min: 0,
      max: 100,
      step: 1,
      onInput: (value: number) => {
        setVolume((prev) => ({ ...prev, game: Math.round(value) / 100 }));
      },
    },
    {
      type: "slider" as const,
      label: "Preview Volume",
      value: () => Math.round(volume().preview * 100),
      min: 0,
      max: 100,
      step: 1,
      onInput: (value: number) => {
        setVolume((prev) => ({ ...prev, preview: Math.round(value) / 100 }));
      },
    },
    {
      type: "slider" as const,
      label: "Menu Volume",
      value: () => Math.round(volume().menu * 100),
      min: 0,
      max: 100,
      step: 1,
      onInput: (value: number) => {
        setVolume((prev) => ({ ...prev, menu: Math.round(value) / 100 }));
      },
    },
    {
      type: "button" as const,
      label: "Save",
      action: saveVolume,
    },
  ];

  const { position, increment, decrement, set } = createLoop(() => inputs.length);

  useNavigation(() => ({
    layer: 0,
    onKeydown(event) {
      if (event.action === "back") {
        onBack();
      } else if (event.action === "up") {
        decrement();
      } else if (event.action === "down") {
        increment();
      } else if (event.action === "confirm") {
        setPressed(true);
      }
    },
    onKeyup(event) {
      if (event.action === "confirm") {
        setPressed(false);
        const input = inputs[position()];
        if (input?.type === "button") {
          input.action();
        }
      }
    },
  }));

  return (
    <Layout
      intent="secondary"
      header={<TitleBar title="Settings" description="Volume" onBack={onBack} />}
      footer={<KeyHints hints={["back", "navigate", "confirm"]} />}
    >
      <div class="flex w-full flex-grow flex-col justify-center">
        <For each={inputs}>
          {(input, index) => {
            if (input.type === "slider") {
              return (
                <Slider
                  selected={position() === index()}
                  gradient="gradient-settings"
                  onMouseEnter={() => set(index())}
                  {...input}
                  value={input.value()}
                />
              );
            }
            return (
              <Button
                selected={position() === index()}
                active={pressed() && position() === index()}
                gradient="gradient-settings"
                onClick={input.action}
                onMouseEnter={() => set(index())}
              >
                {input.label}
              </Button>
            );
          }}
        </For>
      </div>
    </Layout>
  );
}
