// apps/game/src/pages/settings/microphones/[id].tsx
import { useNavigate, useParams } from "@solidjs/router";
import { type Accessor, For, type JSX, Match, Show, Suspense, Switch, createResource, createSignal } from "solid-js";
import { commands } from "~/bindings";
import KeyHints from "~/components/key-hints";
import Layout from "~/components/layout";
import TitleBar from "~/components/title-bar";
import Button from "~/components/ui/button";
import Select from "~/components/ui/select";
import Slider from "~/components/ui/slider";
import { createLoop } from "~/hooks/loop";
import { useNavigation } from "~/hooks/navigation";
import { type Microphone, settingsStore } from "~/stores/settings";
import IconLoaderCircle from "~icons/lucide/loader-circle";

export default function MicrophoneSettings() {
  const [pressed, setPressed] = createSignal(false);
  const navigate = useNavigate();
  const onBack = () => {
    navigate("/settings/microphones");
  };
  const [microphones] = createResource(async () => {
    const response = await commands.getMicrophones();
    if (response.status === "ok") {
      return response.data;
    }

    return [];
  });

  const params = useParams<{ id: string }>();
  const id = () => {
    const id = Number.parseInt(params.id, 10);
    return Number.isNaN(id) ? -1 : id;
  };

  return (
    <Layout
      intent="secondary"
      header={<TitleBar title="Settings" description={"Microphones"} onBack={onBack} />}
      footer={<KeyHints hints={["back", "navigate", "confirm"]} />}
    >
      <Suspense
        fallback={
          <div class="flex flex-grow items-center justify-center">
            <IconLoaderCircle class="animate-spin text-6xl" />
          </div>
        }
      >
        <Show when={microphones()}>
          {(microphones) => {
            const [microphone, setMicrophone] = createSignal(
              settingsStore.microphones()[id()] || {
                name: microphones()[0]?.name || null,
                channel: 1,
                color: "sky",
                delay: 200,
                gain: 1,
                threshold: 2,
              }
            );

            const deleteMicrophone = () => {
              settingsStore.deleteMicrophone(id());
              onBack();
            };

            const saveMicrophone = () => {
              const mic = microphone();
              if (!isValidMicrophone(mic)) {
                return;
              }
              settingsStore.saveMicrophone(id(), mic);
              onBack();
            };

            const inputs: Input[] = [
              {
                type: "select-string",
                label: "Microphone",
                value: () => microphone().name,
                onChange: (name: string) => {
                  setMicrophone((prev) => ({ ...prev, name }));
                },
                options: microphones().map((microphone) => microphone.name),
              },
              {
                type: "select-number",
                label: "Channel",
                value: () => microphone().channel,
                onChange: (channel: number) => {
                  setMicrophone((prev) => ({ ...prev, channel }));
                },
                options: [1, 2, 3, 4, 5, 6, 7, 8],
              },
              {
                type: "select-string",
                label: "Color",
                value: () => microphone().color,
                onChange: (color: string) => {
                  setMicrophone((prev) => ({ ...prev, color }));
                },
                options: ["sky", "red", "blue", "green", "pink", "purple", "yellow", "orange"],
                renderValue: (color: string | null) => (
                  <div
                    class="h-8 w-8 rounded-full border-[0.2cqw] border-white"
                    style={{ background: color ? `var(--color-${color}-500)` : "transparent" }}
                  />
                ),
              },
              {
                type: "slider",
                label: "Delay",
                value: () => microphone().delay,
                min: 0,
                max: 500,
                step: 10,
                onInput: (delay: number) => {
                  setMicrophone((prev) => ({ ...prev, delay }));
                },
              },
              {
                type: "slider",
                label: "Gain",
                value: () => microphone().gain,
                min: 0,
                max: 3,
                step: 0.1,
                onInput: (gain: number) => {
                  setMicrophone((prev) => ({ ...prev, gain }));
                },
              },
              {
                type: "slider",
                label: "Threshold",
                value: () => microphone().threshold,
                min: 0,
                max: 5,
                step: 0.1,
                onInput: (threshold: number) => {
                  setMicrophone((prev) => ({ ...prev, threshold }));
                },
              },
              {
                type: "button",
                label: "Delete",
                action: deleteMicrophone,
              },
              {
                type: "button",
                label: "Save",
                action: saveMicrophone,
              },
            ];

            const { position, increment, decrement, set } = createLoop(() => inputs.length);

            useNavigation(() => ({
              layer: 0,
              onKeydown(event) {
                if (event.action === "back") {
                  onBack();
                } else if (event.action === "up") {
                  decrement();
                } else if (event.action === "down") {
                  increment();
                } else if (event.action === "confirm") {
                  setPressed(true);
                }
              },
              onKeyup(event) {
                if (event.action === "confirm") {
                  setPressed(false);
                  const button = inputs[position()];
                  if (button?.type === "button") {
                    button.action();
                  }
                }
              },
            }));

            return (
              <div class="flex w-full flex-grow flex-col justify-center">
                <For each={inputs}>
                  {(button, index) => (
                    <Switch>
                      <Match when={button.type === "select-string" && button}>
                        {(button) => (
                          <Select
                            selected={position() === index()}
                            gradient="gradient-settings"
                            label={button().label}
                            value={button().value()}
                            options={button().options}
                            onChange={button().onChange}
                            renderValue={button().renderValue}
                            onMouseEnter={() => set(index())}
                          />
                        )}
                      </Match>
                      <Match when={button.type === "select-number" && button}>
                        {(button) => (
                          <Select
                            selected={position() === index()}
                            gradient="gradient-settings"
                            label={button().label}
                            value={button().value()}
                            options={button().options}
                            onChange={button().onChange}
                            onMouseEnter={() => set(index())}
                          />
                        )}
                      </Match>
                      <Match when={button.type === "slider" && button}>
                        {(button) => (
                          <Slider
                            selected={position() === index()}
                            gradient="gradient-settings"
                            onMouseEnter={() => set(index())}
                            {...button()}
                            value={button().value()}
                          />
                        )}
                      </Match>
                      <Match when={button.type === "button" && button}>
                        {(button) => (
                          <Button
                            selected={position() === index()}
                            active={pressed() && position() === index()}
                            gradient="gradient-settings"
                            onClick={button().action}
                            onMouseEnter={() => set(index())}
                          >
                            {button().label}
                          </Button>
                        )}
                      </Match>
                    </Switch>
                  )}
                </For>
              </div>
            );
          }}
        </Show>
      </Suspense>
    </Layout>
  );
}

type NullablePartial<T> = { [P in keyof T]?: T[P] | null };
function isValidMicrophone(microphone: NullablePartial<Microphone>): microphone is Microphone {
  return microphone.name !== null && microphone.channel !== null && microphone.color !== null;
}

type Input =
  | {
      type: "select-string";
      label: string;
      value: Accessor<string | null>;
      onChange: (value: string) => void;
      options: string[];
      renderValue?: (value: string | null) => JSX.Element;
    }
  | {
      type: "select-number";
      label: string;
      value: Accessor<number | null>;
      onChange: (value: number) => void;
      options: number[];
    }
  | {
      type: "slider";
      label: string;
      value: Accessor<number>;
      min: number;
      max: number;
      step: number;
      onInput: (value: number) => void;
    }
  | {
      type: "button";
      label: string;
      action: () => void;
    };

// apps/electron/src/renderer/src/pages/settings/microphones/[id].vue
<script setup lang="ts">
import RangeInput from '@renderer/components/menu/RangeInput.vue'
import ListInput from '@renderer/components/menu/ListInput.vue'
import WideButton from '@renderer/components/menu/WideButton.vue'
import type { MenuNavigationEvent } from '@renderer/composables/useMenuNavigation'
import type { Microphone } from '@renderer/stores/settings'

const router = useRouter()
const route = useRoute()
const settingsStore = useSettingsStore()

const back = () => {
  router.back()
}

const id = computed(() => {
  return parseInt(route.params.id as string)
})

const deleteMicrophone = () => {
  if (id.value === undefined) return
  settingsStore.deleteMicrophone(id.value)
  back()
}

const saveMicrophone = () => {
  if (id.value === undefined) return

  // find id of microphone by label from mediaDevices
  const microphone = mediaDevices.value.find(device => device.label === label.value)

  if (!microphone) return

  const mic: Microphone = {
    delay: delay.value,
    gain: gain.value,
    color: color.value,
    channel: channel.value,
    label: label.value,
    id: microphone?.deviceId,
    threshold: threshold.value,
  }

  settingsStore.saveMicrophone(id.value, mic)
  back()
}

const label = ref('')
const color = ref('#00B5FF')
const channel = ref(1)
const delay = ref(250)
const gain = ref(1)
const threshold = ref(2)

const loading = ref(true)

watch(id, (newId) => {
  const microphone = settingsStore.microphones.at(newId)

  if (!microphone) return
  delay.value = microphone.delay
  gain.value = microphone.gain
  color.value = microphone.color
  channel.value = microphone.channel
  label.value = microphone.label
  threshold.value = microphone.threshold
}, { immediate: true })

const mediaDevices = ref<MediaDeviceInfo[]>([])

const micOptions = computed(() => {
  const options = mediaDevices.value.map(device => device.label)
  return options
})

const buttons = [
  { type: 'list', label: 'Microphone', value: label, options: micOptions, displayType: 'text' },
  { type: 'list', label: 'Color', value: color, options: ref(['#00B5FF', '#FF2E0E']), displayType: 'color' },
  { type: 'list', label: 'Channel', value: channel, options: ref([1, 2, 3]), displayType: 'text' },
  { type: 'range', label: 'Delay', value: delay, min: 0, max: 600, step: 1, clickStep: 10 },
  { type: 'range', label: 'Gain', value: gain, min: 0.5, max: 2, step: 0.1, clickStep: 0.1 },
  { type: 'range', label: 'Threshold', value: threshold, min: 0, max: 5, step: 0.1, clickStep: 0.1 },
  { type: 'button', label: 'Delete', action: deleteMicrophone },
  { type: 'button', label: 'Save', action: saveMicrophone },
] as const

const { position, increment, decrement } = useLoop(buttons.length - 1)

useMenuNavigation(useRepeatThrottleFn(e => onNavigate(e), 150))
const onNavigate = (event: MenuNavigationEvent) => {
  if (event.action === 'confirm') {
    const button = buttons.at(position.value)
    if (button?.type === 'button') button.action()
  } else if (event.action === 'back') {
    back()
  } else if (event.action === 'up') {
    decrement()
    scrollIntoView(position.value)
  } else if (event.action === 'down') {
    increment()
    scrollIntoView(position.value)
  } else if (event.action === 'right') {
    const next = buttonRefs.value.at(position.value)?.next
    if (next) next()
  } else if (event.action === 'left') {
    const prev = buttonRefs.value.at(position.value)?.prev
    if (prev) prev()
  }
}

const scrollIntoView = (index: number) => {
  const el = buttonRefs.value[index]
  if (!el) return
  setTimeout(() => {
    unrefElement<HTMLDivElement>(el)?.scrollIntoView({ behavior: 'smooth', block: 'nearest' })
  }, 5)
}

onMounted(async () => {
  const devices = await navigator.mediaDevices.enumerateDevices()
  mediaDevices.value = devices.filter(device => device.kind === 'audioinput')
  loading.value = false

  if (label.value === '') {
    label.value = micOptions.value[0] ?? ''
  }
})

const gradient = { start: '#36D1DC', end: '#5B86E5' }

const buttonRefs = ref<any[]>([])
const setRefs = (ref: any, index) => {
  buttonRefs.value[index] = ref
}

const select = useSoundEffect('select')
watch(position, () => select.play())

const confirm = useSoundEffect('confirm')

onBeforeUnmount(() => {
  confirm.play()
})
</script>

<template>
  <Layout class="gradient-bg-secondary" @back="back">
    <template #header>
      <TitleBar title="Settings" :description="label" @back="back" />
    </template>

    <div class="flex items-center">
      <div class="max-h-full w-full">
        <template v-for="button, index in buttons">
          <RangeInput
            v-if="button.type === 'range'"
            :key="`range${button.label}`"
            :ref="(el) => setRefs(el, index)"
            v-model="button.value.value"
            :active="index === position"
            :label="button.label"
            :gradient="gradient"
            :min="button.min"
            :max="button.max"
            :step="button.step"
            :click-step="button.clickStep"
            class="w-full"
            @mouseenter="position = index"
          />
          <ListInput
            v-else-if="button.type === 'list'"
            :key="`list${button.label}`"
            :ref="(el) => setRefs(el, index)"
            v-model="button.value.value"
            :active="index === position"
            :label="button.label"
            :gradient="gradient"
            :options="button.options.value"
            :display-type="button.displayType"
            class="w-full"
            @mouseenter="position = index"
          />
          <WideButton
            v-else-if="button.type === 'button'"
            :key="`button${button.label}`"
            :ref="(el) => setRefs(el, index)"
            :label="button.label"
            :gradient="gradient"
            :active="index === position"
            class="w-full"
            @click="button.action"
            @mouseenter="position = index"
          />
        </template>
      </div>
    </div>
    <template #footer>
      <KeyHints :hints="['back', 'confirm']" />
    </template>
  </Layout>
</template>
